server:
    port: 8080
    servlet:
        context-path: /example
        
spring:
  application:
    name: example

  # H2 Database 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: example
    password: asd1234

  # H2 Console 설정
  h2:
    console: # H2 DB를 웹에서 관리할 수 있는 기능
      enabled: true           # H2 Console 사용 여부 
      path: /h2-console       # H2 Console 접속 주소

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update  # 또는 create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  thymeleaf:
    prefix: classpath:/templates/
    enabled: true
    mode: HTML
    cache: false